const express = require('express');
const router = express.Router();
const ticketController = require('../controllers/ticketController');
router.get('/', ticketController.traerTickets);
router.get('/pendientes', ticketController.traerTicketsPendientes);
router.get('/nopendientes', ticketController.traerTicketsNoPendientes);
router.get('/and', ticketController.traerTicketsPendientesYTipoEspecifico);
router.get('/or', ticketController.traerTicketsResueltosOTipoEspecifico);
router.get('/gt', ticketController.traerTicketsCodigoEmpleadoMayor);
router.get('/norGte', ticketController.traerTicketsNoResueltosNiCodigoEmpleadoMayor);
router.get('/lt', ticketController.traerTicketsNumeroPlanMenoresDocientos);
router.get('/lte', ticketController.traerTicketsNumeroPlanMenoresIgual);
router.get('/all', ticketController.traerTicketsConTodosBeneficios);
router.get('/exists', ticketController.traerTicketsConCorreos);
router.get('/textsearch', ticketController.traerTicketsPorTexto);
router.get('/size', ticketController.traerTicketsConNumeroDerivaciones);
router.get('/unwind', ticketController.obtenerTotalBeneficios);
router.get('/match', ticketController.traerTicketsPendientesConEmpleadoMayor);
router.get('/lookup', ticketController.traerTicketsConClientesEmpleados);
router.get('/elemMatch', ticketController.traerTicketsDepCancelacionesSolucionExitosa);
router.get('/geoIntersects', ticketController.traerTicketsGeoIntersect);
router.get('/geoWithin', ticketController.obtenerTicketsAlrededorDeMardel);
module.exports = router;